# Generated by Django 4.2 on 2023-05-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_comment_topicid_alter_reply_commentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replyCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='numberOfComments',
            field=models.IntegerField(default=0),
        ),
    ]
