# Generated by Django 4.2 on 2023-05-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_comment_replycount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isClicked',
            field=models.BooleanField(default=False),
        ),
    ]
