# Generated by Django 4.2 on 2023-05-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_isclicked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='isClicked',
        ),
    ]
